apiVersion: v1
kind: Secret
metadata:
  name: notes-secrets
  namespace: notes-app
type: Opaque
stringData:
  APP_KEY: "base64:PUT_LARAVEL_APP_KEY_HERE"
  JWT_SECRET: "PUT_JWT_SECRET_HERE"
  MYSQL_ROOT_PASSWORD: "PUT_MYSQL_ROOT_PASSWORD_HERE"
